{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pycaret in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (3.0.0rc4)\n",
      "Requirement already satisfied: matplotlib>=3.3.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (3.4.3)\n",
      "Requirement already satisfied: importlib-metadata>=4.12.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (5.0.0)\n",
      "Requirement already satisfied: imbalanced-learn>=0.8.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (0.9.0)\n",
      "Requirement already satisfied: numba~=0.55.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (0.55.2)\n",
      "Requirement already satisfied: category-encoders>=2.4.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (2.5.1.post0)\n",
      "Requirement already satisfied: yellowbrick>=1.4 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.4)\n",
      "Requirement already satisfied: pmdarima!=1.8.1,<2.0.0,>=1.8.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.8.5)\n",
      "Requirement already satisfied: psutil>=5.9.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (5.9.2)\n",
      "Requirement already satisfied: jinja2>=1.2 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (3.1.2)\n",
      "Requirement already satisfied: tbats>=1.1.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.1.1)\n",
      "Requirement already satisfied: plotly>=5.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (5.5.0)\n",
      "Requirement already satisfied: lightgbm>=3.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (3.3.2)\n",
      "Requirement already satisfied: scikit-plot>=0.3.7 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (0.3.7)\n",
      "Requirement already satisfied: scipy<1.9.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.8.1)\n",
      "Requirement already satisfied: pandas<1.5.0,>=1.3.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.4.4)\n",
      "Requirement already satisfied: tqdm>=4.62.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (4.62.3)\n",
      "Requirement already satisfied: joblib>=1.1.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.1.0)\n",
      "Requirement already satisfied: kaleido>=0.2.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (0.2.1)\n",
      "Requirement already satisfied: ipywidgets>=7.6.5 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (7.6.5)\n",
      "Requirement already satisfied: markupsafe>=2.0.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (2.1.1)\n",
      "Requirement already satisfied: sktime~=0.13.2 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (0.13.4)\n",
      "Requirement already satisfied: pyod>=0.9.8 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.0.5)\n",
      "Requirement already satisfied: statsmodels>=0.12.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (0.13.2)\n",
      "Requirement already satisfied: numpy<1.23,>=1.21 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.22.4)\n",
      "Requirement already satisfied: scikit-learn>=1.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (1.0.2)\n",
      "Requirement already satisfied: requests>=2.27.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (2.28.1)\n",
      "Requirement already satisfied: ipython>=5.5.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (7.29.0)\n",
      "Requirement already satisfied: schemdraw>=0.14 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (0.15)\n",
      "Requirement already satisfied: plotly-resampler>=0.7.2.2 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pycaret) (0.8.2rc3)\n",
      "Requirement already satisfied: patsy>=0.5.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from category-encoders>=2.4.0->pycaret) (0.5.2)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from imbalanced-learn>=0.8.1->pycaret) (2.2.0)\n",
      "Requirement already satisfied: zipp>=0.5 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from importlib-metadata>=4.12.0->pycaret) (3.6.0)\n",
      "Requirement already satisfied: setuptools>=18.5 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (58.0.4)\n",
      "Requirement already satisfied: appnope in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.1.2)\n",
      "Requirement already satisfied: pickleshare in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.7.5)\n",
      "Requirement already satisfied: traitlets>=4.2 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (5.1.0)\n",
      "Requirement already satisfied: pexpect>4.3 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (4.8.0)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (3.0.20)\n",
      "Requirement already satisfied: jedi>=0.16 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.18.0)\n",
      "Requirement already satisfied: backcall in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.2.0)\n",
      "Requirement already satisfied: decorator in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (5.1.0)\n",
      "Requirement already satisfied: matplotlib-inline in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (0.1.2)\n",
      "Requirement already satisfied: pygments in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipython>=5.5.0->pycaret) (2.10.0)\n",
      "Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (3.5.1)\n",
      "Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (1.0.0)\n",
      "Requirement already satisfied: ipython-genutils~=0.2.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.0)\n",
      "Requirement already satisfied: nbformat>=4.2.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (5.1.3)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipywidgets>=7.6.5->pycaret) (6.4.1)\n",
      "Requirement already satisfied: jupyter-client<8.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (6.1.12)\n",
      "Requirement already satisfied: tornado<7.0,>=4.2 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (6.1)\n",
      "Requirement already satisfied: debugpy<2.0,>=1.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (1.4.1)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.2)\n",
      "Requirement already satisfied: jupyter-core>=4.6.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (4.8.1)\n",
      "Requirement already satisfied: python-dateutil>=2.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (2.8.2)\n",
      "Requirement already satisfied: pyzmq>=13 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (22.2.1)\n",
      "Requirement already satisfied: wheel in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from lightgbm>=3.0.0->pycaret) (0.37.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->pycaret) (0.10.0)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->pycaret) (3.0.4)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->pycaret) (1.3.1)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=3.3.0->pycaret) (8.4.0)\n",
      "Requirement already satisfied: six in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.3.0->pycaret) (1.16.0)\n",
      "Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets>=7.6.5->pycaret) (3.2.0)\n",
      "Requirement already satisfied: pyrsistent>=0.14.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.6.5->pycaret) (0.18.0)\n",
      "Requirement already satisfied: attrs>=17.4.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.6.5->pycaret) (21.2.0)\n",
      "Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from numba~=0.55.0->pycaret) (0.38.1)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pandas<1.5.0,>=1.3.0->pycaret) (2021.3)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pexpect>4.3->ipython>=5.5.0->pycaret) (0.7.0)\n",
      "Requirement already satisfied: tenacity>=6.2.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from plotly>=5.0.0->pycaret) (8.0.1)\n",
      "Requirement already satisfied: orjson<4.0.0,>=3.7.7 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from plotly-resampler>=0.7.2.2->pycaret) (3.8.0)\n",
      "Requirement already satisfied: jupyter-dash>=0.4.2 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from plotly-resampler>=0.7.2.2->pycaret) (0.4.2)\n",
      "Requirement already satisfied: dash<3.0.0,>=2.2.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from plotly-resampler>=0.7.2.2->pycaret) (2.6.2)\n",
      "Requirement already satisfied: Flask-Cors<4.0.0,>=3.0.10 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from plotly-resampler>=0.7.2.2->pycaret) (3.0.10)\n",
      "Requirement already satisfied: trace-updater>=0.0.8 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from plotly-resampler>=0.7.2.2->pycaret) (0.0.8)\n",
      "Requirement already satisfied: Flask>=1.0.4 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from dash<3.0.0,>=2.2.0->plotly-resampler>=0.7.2.2->pycaret) (2.2.2)\n",
      "Requirement already satisfied: dash-core-components==2.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from dash<3.0.0,>=2.2.0->plotly-resampler>=0.7.2.2->pycaret) (2.0.0)\n",
      "Requirement already satisfied: dash-html-components==2.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from dash<3.0.0,>=2.2.0->plotly-resampler>=0.7.2.2->pycaret) (2.0.0)\n",
      "Requirement already satisfied: dash-table==5.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from dash<3.0.0,>=2.2.0->plotly-resampler>=0.7.2.2->pycaret) (5.0.0)\n",
      "Requirement already satisfied: flask-compress in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from dash<3.0.0,>=2.2.0->plotly-resampler>=0.7.2.2->pycaret) (1.13)\n",
      "Requirement already satisfied: click>=8.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from Flask>=1.0.4->dash<3.0.0,>=2.2.0->plotly-resampler>=0.7.2.2->pycaret) (8.0.3)\n",
      "Requirement already satisfied: Werkzeug>=2.2.2 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from Flask>=1.0.4->dash<3.0.0,>=2.2.0->plotly-resampler>=0.7.2.2->pycaret) (2.2.2)\n",
      "Requirement already satisfied: itsdangerous>=2.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from Flask>=1.0.4->dash<3.0.0,>=2.2.0->plotly-resampler>=0.7.2.2->pycaret) (2.0.1)\n",
      "Requirement already satisfied: retrying in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from jupyter-dash>=0.4.2->plotly-resampler>=0.7.2.2->pycaret) (1.3.3)\n",
      "Requirement already satisfied: ansi2html in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from jupyter-dash>=0.4.2->plotly-resampler>=0.7.2.2->pycaret) (1.8.0)\n",
      "Requirement already satisfied: nest-asyncio in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from jupyter-dash>=0.4.2->plotly-resampler>=0.7.2.2->pycaret) (1.5.1)\n",
      "Requirement already satisfied: Cython!=0.29.18,>=0.29 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pmdarima!=1.8.1,<2.0.0,>=1.8.0->pycaret) (0.29.24)\n",
      "Requirement already satisfied: urllib3 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from pmdarima!=1.8.1,<2.0.0,>=1.8.0->pycaret) (1.26.7)\n",
      "Requirement already satisfied: wcwidth in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.5.0->pycaret) (0.2.5)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.27.1->pycaret) (2021.10.8)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.27.1->pycaret) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.27.1->pycaret) (3.2)\n",
      "Requirement already satisfied: deprecated>=1.2.13 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from sktime~=0.13.2->pycaret) (1.2.13)\n",
      "Requirement already satisfied: wrapt<2,>=1.10 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from deprecated>=1.2.13->sktime~=0.13.2->pycaret) (1.12.1)\n",
      "Requirement already satisfied: packaging>=21.3 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from statsmodels>=0.12.1->pycaret) (21.3)\n",
      "Requirement already satisfied: notebook>=4.4.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (6.4.5)\n",
      "Requirement already satisfied: Send2Trash>=1.5.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (1.8.0)\n",
      "Requirement already satisfied: prometheus-client in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (0.11.0)\n",
      "Requirement already satisfied: argon2-cffi in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (20.1.0)\n",
      "Requirement already satisfied: nbconvert in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (6.1.0)\n",
      "Requirement already satisfied: terminado>=0.8.3 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (0.9.4)\n",
      "Requirement already satisfied: cffi>=1.0.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (1.14.6)\n",
      "Requirement already satisfied: pycparser in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (2.20)\n",
      "Requirement already satisfied: brotli in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from flask-compress->dash<3.0.0,>=2.2.0->plotly-resampler>=0.7.2.2->pycaret) (1.0.9)\n",
      "Requirement already satisfied: mistune<2,>=0.8.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (0.8.4)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (1.4.3)\n",
      "Requirement already satisfied: jupyterlab-pygments in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (0.1.2)\n",
      "Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (0.5.3)\n",
      "Requirement already satisfied: bleach in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (4.0.0)\n",
      "Requirement already satisfied: entrypoints>=0.2.2 in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (0.3)\n",
      "Requirement already satisfied: testpath in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (0.5.0)\n",
      "Requirement already satisfied: defusedxml in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (0.7.1)\n",
      "Requirement already satisfied: async-generator in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (1.10)\n",
      "Requirement already satisfied: webencodings in /Users/sage/opt/anaconda3/lib/python3.9/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.6.5->pycaret) (0.5.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "zsh:1: no matches found: pycaret[models]\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting cuml\n",
      "  Using cached cuml-0.6.1.post1.tar.gz (1.1 kB)\n",
      "Building wheels for collected packages: cuml\n",
      "  Building wheel for cuml (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Users/sage/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d /private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-wheel-shgb6pcl\n",
      "       cwd: /private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/\n",
      "  Complete output (25 lines):\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  installing to build/bdist.macosx-10.9-x86_64/wheel\n",
      "  running install\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py\", line 18, in <module>\n",
      "      setup(name=pkg,\n",
      "    File \"/Users/sage/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"/Users/sage/opt/anaconda3/lib/python3.9/distutils/core.py\", line 148, in setup\n",
      "      dist.run_commands()\n",
      "    File \"/Users/sage/opt/anaconda3/lib/python3.9/distutils/dist.py\", line 966, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"/Users/sage/opt/anaconda3/lib/python3.9/distutils/dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"/Users/sage/opt/anaconda3/lib/python3.9/site-packages/wheel/bdist_wheel.py\", line 335, in run\n",
      "      self.run_command('install')\n",
      "    File \"/Users/sage/opt/anaconda3/lib/python3.9/distutils/cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"/Users/sage/opt/anaconda3/lib/python3.9/distutils/dist.py\", line 985, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py\", line 15, in run\n",
      "      raise Exception(long_description)\n",
      "  Exception: Please install cuml via the rapidsai conda channel. See https://rapids.ai/start.html for instructions.\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[31m  ERROR: Failed building wheel for cuml\u001b[0m\n",
      "\u001b[?25h  Running setup.py clean for cuml\n",
      "Failed to build cuml\n",
      "Installing collected packages: cuml\n",
      "    Running setup.py install for cuml ... \u001b[?25lerror\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/sage/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-record-dcw9slln/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sage/opt/anaconda3/include/python3.9/cuml\n",
      "         cwd: /private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/\n",
      "    Complete output (16 lines):\n",
      "    running install\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py\", line 18, in <module>\n",
      "        setup(name=pkg,\n",
      "      File \"/Users/sage/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/Users/sage/opt/anaconda3/lib/python3.9/distutils/core.py\", line 148, in setup\n",
      "        dist.run_commands()\n",
      "      File \"/Users/sage/opt/anaconda3/lib/python3.9/distutils/dist.py\", line 966, in run_commands\n",
      "        self.run_command(cmd)\n",
      "      File \"/Users/sage/opt/anaconda3/lib/python3.9/distutils/dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py\", line 15, in run\n",
      "        raise Exception(long_description)\n",
      "    Exception: Please install cuml via the rapidsai conda channel. See https://rapids.ai/start.html for instructions.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[31mERROR: Command errored out with exit status 1: /Users/sage/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-install-2hx5ouv2/cuml_123a75db01a04076a74a2ecd46a59a8a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/pip-record-dcw9slln/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sage/opt/anaconda3/include/python3.9/cuml Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25hNote: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "ename": "OSError",
     "evalue": "dlopen(/Users/sage/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'\n  Referenced from: '/Users/sage/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so'\n  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOSError\u001b[0m                                   Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/sg/8dmzq1nn0wl6qmndt2sf_m1r0000gn/T/ipykernel_34953/886475183.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun_line_magic\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'pip'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'install pycaret[models]'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun_line_magic\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'pip'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'install cuml'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mlightgbm\u001b[0m \u001b[0;32mimport\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mimport\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mdatetime\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mdatetime\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/lightgbm/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mpathlib\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mPath\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 8\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mbasic\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mBooster\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mDataset\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mSequence\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mregister_logger\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      9\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mcallback\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mearly_stopping\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlog_evaluation\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mprint_evaluation\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrecord_evaluation\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mreset_parameter\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mengine\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mCVBooster\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcv\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtrain\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/lightgbm/basic.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m    108\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    109\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 110\u001b[0;31m \u001b[0m_LIB\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_load_lib\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    111\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    112\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/lightgbm/basic.py\u001b[0m in \u001b[0;36m_load_lib\u001b[0;34m()\u001b[0m\n\u001b[1;32m     99\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlib_path\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    100\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 101\u001b[0;31m     \u001b[0mlib\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mctypes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcdll\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mLoadLibrary\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlib_path\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    102\u001b[0m     \u001b[0mlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mLGBM_GetLastError\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrestype\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mctypes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mc_char_p\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    103\u001b[0m     \u001b[0mcallback\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mctypes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mCFUNCTYPE\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mctypes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mc_char_p\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/ctypes/__init__.py\u001b[0m in \u001b[0;36mLoadLibrary\u001b[0;34m(self, name)\u001b[0m\n\u001b[1;32m    458\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    459\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mLoadLibrary\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 460\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_dlltype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    461\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    462\u001b[0m     \u001b[0m__class_getitem__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mclassmethod\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_types\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mGenericAlias\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/ctypes/__init__.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, name, mode, handle, use_errno, use_last_error, winmode)\u001b[0m\n\u001b[1;32m    380\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    381\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mhandle\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 382\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_handle\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_dlopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmode\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    383\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    384\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_handle\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mhandle\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mOSError\u001b[0m: dlopen(/Users/sage/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'\n  Referenced from: '/Users/sage/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so'\n  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)"
     ]
    }
   ],
   "source": [
    "%pip install pycaret \n",
    "%pip install pycaret[models]\n",
    "%pip install cuml\n",
    "from lightgbm import*\n",
    "from pandas import*\n",
    "from datetime import datetime\n",
    "from numpy import*\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "from lightgbm import*\n",
    "# We'll also import seaborn, a Python graphing library\n",
    "import warnings # current version of seaborn generates a bunch of warnings that we'll ignore\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "import seaborn as sns\n",
    "sns.set(style=\"white\", color_codes=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# load dataset\n",
    "from pycaret.datasets import get_data\n",
    "insurance = get_data('insurance')\n",
    "\n",
    "# init environment\n",
    "from pycaret.regression import *\n",
    "r1 = setup(insurance,\n",
    "           target = 'charges',\n",
    "           session_id = 122,\n",
    "           normalize = True\n",
    "           polynomial_features = True,\n",
    "           trigonometry_features = True,\n",
    "           feature_interaction=True,\n",
    "           bin_numeric_features= ['age', 'bmi']\n",
    "          )\n",
    "#Model training and selection\n",
    "best_lr= compare_models()\n",
    "\n",
    "# Analyse best model\n",
    "evaluate_model(best_lr)\n",
    "\n",
    "# predictions on new data\n",
    "predictions = predict_models(best_lr)\n",
    "\n",
    "# save pipeline/model\n",
    "save_model(best_lr,'MLOps_Pipeline')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "vscode": {
   "interpreter": {
    "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
